### ISSUE TITLE
Fails to generate colors for small values

### ISSUE THREAD

**Issue by dkoprowski** [dominicegginton/hex-color-opacity#3]
Hi, I've found a bug that when opacity value is really small (like 1% - 4%) function will generate wrong hex.

## Failing test example:
```
    Expected: "#FF700003"
    Received: "#FF70003"

      32 |   it('returns proper values', () => {
      33 |     expect(opacity('#FF7000', 0.0)).toBe('#FF700000')
    > 34 |     expect(opacity('#FF7000', 0.01)).toBe('#FF700003')
```

## Fix
To fix I changed those lines:
```
  if (opacity === 0) color += '00'
  else if (opacity !== 1) color += Math.round(opacity * 255).toString(16)
  return `#${color}`
```
into this:

```
  const hexOpacity = Math.round(percentage * 255)
    .toString(16)
    .padStart(2, '0')
    .toUpperCase()

  return `#${color}${hexOpacity}`
```

This adds zeros at the beginning if generated opacity doesn't contain 2 characters. This also works for 0.0 value so no `if` needed.

**Comment by dominicegginton** [comment]
Hi @dkoprowski, a fix has been merged and will be released in 0.1.2 soon. Thanks for reporting 😄
